"""empty message

Revision ID: 6c9437c8e57b
Revises: 
Create Date: 2024-10-04 21:40:50.083486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6c9437c8e57b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breed_name'), 'breed', ['name'], unique=True)
    op.create_table('color',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_name'), 'color', ['name'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('kitten',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('color_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitten_age'), 'kitten', ['age'], unique=False)
    op.create_index(op.f('ix_kitten_breed_id'), 'kitten', ['breed_id'], unique=False)
    op.create_index(op.f('ix_kitten_color_id'), 'kitten', ['color_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kitten_color_id'), table_name='kitten')
    op.drop_index(op.f('ix_kitten_breed_id'), table_name='kitten')
    op.drop_index(op.f('ix_kitten_age'), table_name='kitten')
    op.drop_table('kitten')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_color_name'), table_name='color')
    op.drop_table('color')
    op.drop_index(op.f('ix_breed_name'), table_name='breed')
    op.drop_table('breed')
    # ### end Alembic commands ###
